server:
  port: 8999
  servlet:
    context-path: /demoui
spring:
  profiles: alone
  application:
    name: cpaas-admin-ui
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    #password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
      #连接超时时间
    timeout: 10000
logging:
  config: classpath:log4j2.xml
  
ui:
  type: ${GATETYPE:header}   #header,path
  api-url: ${GATEIP:http://localhost}:${GATEPORT:8200}/api #http://127.0.0.1:8100/api(集群网关模式)