
server:
  port: 8200
  servlet:
    context-path: /api/
  #jetty配置，主要是acceptors和selectors
  jetty:
    acceptors: 2
    selectors: 4
  #tomcat的配置可以保留，切换回来可用，反正不会生效
  tomcat:
      remote-ip-header: x-forward-for
      uri-encoding: UTF-8
      max-threads: 2000
      #background-processor-delay: 30
      max-http-header-size: 8096
      basedir: ${user.home}/tomcat/tmp
      max-connections: 5000
      max-http-post-size: 10000000
  connection-timeout: 600000

spring:
  profiles: alone
  application:
    name: cpaas-all
  datasource:
    name: cpaas-admin-db
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
        #监控统计拦截的filters
      - key: dn1
        url: jdbc:mysql://localhost:3306/cpaas_admin_db?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        minPoolSize: 5
        maxPoolSize: 20
        borrowConnectionTimeout: 60
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'ZTM' FROM DUAL
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        maxWait: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    #password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
      #连接超时时间
    timeout: 10000
        
        
#-----------------------

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  basepackage: com.cloudpaas.admin.mapper

logging:
  config: classpath:log4j2.xml

  
jwt:
  rsa-secret: 123456
