
server:
  port: 8200
  servlet:
    context-path: /api/

spring:
  application:
    name: cpaas-all
  datasource:
    name: cpaas-admin-db
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
        #监控统计拦截的filters
      - key: dn1
        url: jdbc:mysql://localhost:3306/cpaas_admin_db?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        minPoolSize: 5
        maxPoolSize: 20
        borrowConnectionTimeout: 60
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'ZTM' FROM DUAL
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        maxWait: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2
        
        
#-----------------------

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  basepackage: com.cloudpaas.admin.mapper

logging:
  config: classpath:log4j2.xml
