server:
  port: 8888
  servlet:
    context-path: /adminui
spring:
  profiles: sentinel
  application:
    name: cpaas-admin-ui
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    database: 0
    #password: 
    sentinel:
      #哨兵监听的master名称
      master: mymaster
      #哨兵地址列表，多个以,分割
      nodes: 127.0.0.1:26001,127.0.0.1:26002,127.0.0.1:26003
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000
logging:
  config: classpath:log4j2.xml
  
  
adminui:
  type: path   #header,path
  api-url: "http://127.0.0.1:8100/api" #http://127.0.0.1:8100/api(集群网关模式)