eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

# 打开健康检查，2.0开始，actuator默认不开放，所以要设置为开发
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: ALWAYS

server:
  port: 8101
  servlet:
    context-path: /admin/

spring:
  application:
    name: cpaas-admin
  boot:          #添加到springbootadmin服务治理
    admin:
      client:
        url: "http://localhost:8901"
        password: password
        username: user
        instance:
          prefer-ip: true
  zipkin:        #添加到链路追踪
    base-url: http://localhost:8902
  sleuth:        #打开日志收集
    enabled: true
    http:
      legacy:
        enabled: true
  datasource:
    name: cpaas-admin-db
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
        #监控统计拦截的filters
      - key: dn1
        url: jdbc:mysql://localhost:3306/cpaas_admin_db?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        minPoolSize: 5
        maxPoolSize: 20
        borrowConnectionTimeout: 60
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'ZTM' FROM DUAL
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        maxWait: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2
        
        
#-----------------------

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  basepackage: com.cloudpaas.admin.mapper

logging:
  config: classpath:log4j2.xml
