eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: ALWAYS

server:
  port: 8101

spring:
  application:
    name: cpaas-admin
  boot:
    admin:
      client:
        url: "http://localhost:8901"
        password: password
        username: user
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://localhost:8902
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
